# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    authentication.handler.login_success_handler:
        class:  Proc\UserBundle\Redirection\AfterLoginRedirection
        arguments:  ['@router', '@security.authorization_checker']