<?php

namespace Proc\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntiteRepository extends EntityRepository
{
    public function getCodeEntiteGroupe()
    {
        //$fields = ['d.codeEntite', 'o.codeGroupUser'];
        $qb = $this->createQueryBuilder('a');

        return $qb;
    }
}
