<?php

namespace Proc\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupeUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeUserRepository extends EntityRepository
{
}
