<?php

namespace Proc\IndicateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Mode_calculRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mode_calculRepository extends EntityRepository
{
}
