<?php

namespace Proc\IndicateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SousSecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousSecteurRepository extends EntityRepository
{
}
