<?php

namespace Proxies\__CG__\ProjetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Descriptif_par_ui extends \ProjetBundle\Entity\Descriptif_par_ui implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'id', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'explicationDescParUi', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'baselineDescParUi', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'objectifDescParUi', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'realCumulParUi', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'communes', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'unites', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'indicateur', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'situationAnnuelles', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'activite');
        }

        return array('__isInitialized__', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'id', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'explicationDescParUi', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'baselineDescParUi', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'objectifDescParUi', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'realCumulParUi', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'communes', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'unites', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'indicateur', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'situationAnnuelles', '' . "\0" . 'ProjetBundle\\Entity\\Descriptif_par_ui' . "\0" . 'activite');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Descriptif_par_ui $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setExplicationDescParUi($explicationDescParUi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExplicationDescParUi', array($explicationDescParUi));

        return parent::setExplicationDescParUi($explicationDescParUi);
    }

    /**
     * {@inheritDoc}
     */
    public function getExplicationDescParUi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExplicationDescParUi', array());

        return parent::getExplicationDescParUi();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaselineDescParUi($baselineDescParUi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaselineDescParUi', array($baselineDescParUi));

        return parent::setBaselineDescParUi($baselineDescParUi);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaselineDescParUi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaselineDescParUi', array());

        return parent::getBaselineDescParUi();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjectifDescParUi($objectifDescParUi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjectifDescParUi', array($objectifDescParUi));

        return parent::setObjectifDescParUi($objectifDescParUi);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectifDescParUi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectifDescParUi', array());

        return parent::getObjectifDescParUi();
    }

    /**
     * {@inheritDoc}
     */
    public function setRealCumulParUi($realCumulParUi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRealCumulParUi', array($realCumulParUi));

        return parent::setRealCumulParUi($realCumulParUi);
    }

    /**
     * {@inheritDoc}
     */
    public function getRealCumulParUi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRealCumulParUi', array());

        return parent::getRealCumulParUi();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommune(\ZoneBundle\Entity\Commune $communes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommune', array($communes));

        return parent::addCommune($communes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommune(\ZoneBundle\Entity\Commune $communes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommune', array($communes));

        return parent::removeCommune($communes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommunes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommunes', array());

        return parent::removeCommunes();
    }

    /**
     * {@inheritDoc}
     */
    public function getCommunes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommunes', array());

        return parent::getCommunes();
    }

    /**
     * {@inheritDoc}
     */
    public function addUnite(\Proc\IndicateurBundle\Entity\Unite $unites)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUnite', array($unites));

        return parent::addUnite($unites);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUnite(\Proc\IndicateurBundle\Entity\Unite $unites)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUnite', array($unites));

        return parent::removeUnite($unites);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUnites()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUnites', array());

        return parent::removeUnites();
    }

    /**
     * {@inheritDoc}
     */
    public function getUnites()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnites', array());

        return parent::getUnites();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndicateur(\Proc\IndicateurBundle\Entity\Indicateur $indicateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndicateur', array($indicateur));

        return parent::setIndicateur($indicateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndicateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndicateur', array());

        return parent::getIndicateur();
    }

    /**
     * {@inheritDoc}
     */
    public function addSituationAnnuelle(\ProjetBundle\Entity\SituationAnnuelle $situationAnnuelles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSituationAnnuelle', array($situationAnnuelles));

        return parent::addSituationAnnuelle($situationAnnuelles);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSituationAnnuelle(\ProjetBundle\Entity\SituationAnnuelle $situationAnnuelles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSituationAnnuelle', array($situationAnnuelles));

        return parent::removeSituationAnnuelle($situationAnnuelles);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituationAnnuelles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituationAnnuelles', array());

        return parent::getSituationAnnuelles();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivite(\ProjetBundle\Entity\ActiviteComposante $activite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivite', array($activite));

        return parent::setActivite($activite);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivite', array());

        return parent::getActivite();
    }

}
