<?php

namespace Proxies\__CG__\ProjetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SituationAnnuelle extends \ProjetBundle\Entity\SituationAnnuelle implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'id', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'anneeSitAnParUi', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'valeurCible', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'realGlobSitAnParUi', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'realisationCumule', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'ecartAnnee', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'realisationTrimestres', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'objectifTrimestres', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'descriptifParUi');
        }

        return array('__isInitialized__', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'id', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'anneeSitAnParUi', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'valeurCible', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'realGlobSitAnParUi', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'realisationCumule', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'ecartAnnee', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'realisationTrimestres', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'objectifTrimestres', '' . "\0" . 'ProjetBundle\\Entity\\SituationAnnuelle' . "\0" . 'descriptifParUi');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SituationAnnuelle $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneeSitAnParUi($anneeSitAnParUi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneeSitAnParUi', array($anneeSitAnParUi));

        return parent::setAnneeSitAnParUi($anneeSitAnParUi);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneeSitAnParUi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneeSitAnParUi', array());

        return parent::getAnneeSitAnParUi();
    }

    /**
     * {@inheritDoc}
     */
    public function setValeurCible($valeurCible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValeurCible', array($valeurCible));

        return parent::setValeurCible($valeurCible);
    }

    /**
     * {@inheritDoc}
     */
    public function getValeurCible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValeurCible', array());

        return parent::getValeurCible();
    }

    /**
     * {@inheritDoc}
     */
    public function setRealGlobSitAnParUi($realGlobSitAnParUi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRealGlobSitAnParUi', array($realGlobSitAnParUi));

        return parent::setRealGlobSitAnParUi($realGlobSitAnParUi);
    }

    /**
     * {@inheritDoc}
     */
    public function getRealGlobSitAnParUi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRealGlobSitAnParUi', array());

        return parent::getRealGlobSitAnParUi();
    }

    /**
     * {@inheritDoc}
     */
    public function setRealisationCumule($realisationCumule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRealisationCumule', array($realisationCumule));

        return parent::setRealisationCumule($realisationCumule);
    }

    /**
     * {@inheritDoc}
     */
    public function getRealisationCumule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRealisationCumule', array());

        return parent::getRealisationCumule();
    }

    /**
     * {@inheritDoc}
     */
    public function setEcartAnnee($ecartAnnee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEcartAnnee', array($ecartAnnee));

        return parent::setEcartAnnee($ecartAnnee);
    }

    /**
     * {@inheritDoc}
     */
    public function getEcartAnnee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEcartAnnee', array());

        return parent::getEcartAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function addRealisationTrimestre(\ProjetBundle\Entity\RealisationTrimestre $realisationTrimestres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRealisationTrimestre', array($realisationTrimestres));

        return parent::addRealisationTrimestre($realisationTrimestres);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRealisationTrimestre(\ProjetBundle\Entity\RealisationTrimestre $realisationTrimestres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRealisationTrimestre', array($realisationTrimestres));

        return parent::removeRealisationTrimestre($realisationTrimestres);
    }

    /**
     * {@inheritDoc}
     */
    public function getRealisationTrimestres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRealisationTrimestres', array());

        return parent::getRealisationTrimestres();
    }

    /**
     * {@inheritDoc}
     */
    public function addObjectifTrimestre(\ProjetBundle\Entity\ObjectifTrimestre $objectifTrimestres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addObjectifTrimestre', array($objectifTrimestres));

        return parent::addObjectifTrimestre($objectifTrimestres);
    }

    /**
     * {@inheritDoc}
     */
    public function removeObjectifTrimestre(\ProjetBundle\Entity\ObjectifTrimestre $objectifTrimestres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeObjectifTrimestre', array($objectifTrimestres));

        return parent::removeObjectifTrimestre($objectifTrimestres);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectifTrimestres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectifTrimestres', array());

        return parent::getObjectifTrimestres();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptifParUi(\ProjetBundle\Entity\Descriptif_par_ui $descriptifParUi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptifParUi', array($descriptifParUi));

        return parent::setDescriptifParUi($descriptifParUi);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptifParUi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptifParUi', array());

        return parent::getDescriptifParUi();
    }

}
