<?php

namespace ProjetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Descriptif_projetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Descriptif_projetRepository extends EntityRepository
{
}
