<?php

namespace ProjetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RealisationTrimestreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisationTrimestreRepository extends EntityRepository
{
}
